config/routes.rb
Ilan::Application.routes.draw do
  root "home_page#index"
  
  get "home_page/index"

  resources :categories, only: :show do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :cities, only: :show

  resources :nodes, only: [:show, :new, :create]

  namespace :control do
    get "/" => "base#index"
    resources :nodes, only: [:index, :update]
    resources :categories, except: :show
    resources :cities, except: [:show]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  DEFAULT_ICON = "bullhorn"

  # Validates
  validates :name, presence: true, uniqueness: true
  validates :icon, presence: true

  # Associations
  has_many :nodes

  # Callbacks
  before_validation :default_icon

  private

  def default_icon
    self.icon = DEFAULT_ICON if icon.blank?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @nodes = @category.
              nodes.
              with_published_state.
              where(city_id: current_city.id).
              order(:updated_at).
              page(params[:page]).
              per(20)
  end
end

app/controllers/control/base_controller.rb
module Control
  class BaseController < ApplicationController
    before_action :set_default_breadcrumb
    layout "control"
    http_basic_authenticate_with  name:     ENV['CONTROL_USERNAME'],
                                  password: ENV["CONTROL_PASSWORD"]

    def index
    end

    private

      def set_default_breadcrumb
        unless params[:controller] == "control/base" and params[:action] == "index"
          breadcrumbs.item I18n.t('control'), control_path
        end
      end
  end
end

app/controllers/control/categories_controller.rb
module Control
  class CategoriesController < BaseController
    before_action :set_category, only: [:edit, :update, :destroy]
    before_action :set_breadcrumb, except: :index

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def edit
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to control_categories_path, notice: I18n.t('categories.flash.created')
      else
        flash[:alert] = I18n.t('categories.flash.not_created')
        render action: 'new'
      end
    end

    def update
      if @category.update(category_params)
        redirect_to control_categories_path, notice: I18n.t('categories.flash.updated')
      else
        flash[:alert] = I18n.t('categories.flash.not_updated')
        render action: 'edit'
      end
    end

    def destroy
      @category.destroy
      redirect_to control_categories_url
    end

    private
      def set_category
        @category = Category.find(params[:id])
      end

      def category_params
        params.require(:category).permit(:name, :icon)
      end

      def set_breadcrumb
        breadcrumbs.item t('categories.index.categories'), control_categories_path
      end
  end
end

app/controllers/control/cities_controller.rb
module Control
  class CitiesController < BaseController
    before_action :set_city, only: [:edit, :update, :destroy]
    before_action :set_breadcrumb, except: :index

    def index
      @cities = City.all
    end

    def new
      @city = City.new
    end

    def edit
    end

    def create
      @city = City.new(city_params)

      if @city.save
        redirect_to control_cities_path, notice: I18n.t('cities.flash.created')
      else
        flash[:alert] = I18n.t('cities.flash.not_created')
        render action: 'new'
      end
    end

    def update
      if @city.update(city_params)
        redirect_to control_cities_path, notice: I18n.t('cities.flash.updated')
      else
        flash[:alert] = I18n.t('cities.flash.not_updated')
        render action: 'edit'
      end
    end

    def destroy
      @city.destroy
        redirect_to control_cities_path
    end

    private
      def set_city
        @city = City.find(params[:id])
      end

      def city_params
        params.require(:city).permit(:name)
      end

      def set_breadcrumb
        breadcrumbs.item t('cities.index.cities'), control_cities_path
      end
  end
end

app/controllers/control/nodes_controller.rb
require 'node_filter'

module Control
  class NodesController < BaseController
    def index
      @node_filter = NodeFilter.new(params[:node_filter] || {})
      @nodes = Node.where(status: @node_filter.status)
    end

    def update
      @node = Node.find(params[:id])
      @node.send(:"#{params[:event]}!")
      redirect_to control_nodes_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def icon name
    content_tag :i, nil, class: "glyphicon glyphicon-#{name}"
  end

  def name_with_icon item
    "%s %s".html_safe % [icon(item.icon), item.name]
  end

  def category_name_with_icon category
    category && name_with_icon(category) || nil
  end

end

app/helpers/control/base_helper.rb
module Control::BaseHelper
  def logout_url
    protocol  = url_options[:protocol]
    user      = "invalid@"
    host      = url_options[:host]
    port      = ":" + url_options[:port].to_s
    path      = control_path
    [protocol, user, host, port, path].join
  end
end

app/views/control/categories/_form.html.erb
<%= simple_form_for(['control', @category], html: {class: "form-horizontal"}) do |f| %>
  <%= f.input :name %>
  <%= f.input :icon %>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit, class: "btn-primary" %>
    </div>
  </div>
<% end %>

app/views/control/categories/edit.html.erb
<%= page_title t('categories.edit.editing_category') %>
<% breadcrumbs.item t('categories.edit.editing_category') %>

<%= render 'form' %>

app/views/control/categories/index.html.erb
<%= page_title t('categories.index.categories') %>
<% breadcrumbs.item t('categories.index.categories') %>


<table class="table">
  <thead>
    <tr>
      <th><%=t 'categories.index.category' %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= icon category.icon %> <%= category.name %></td>
        <td><%= link_to t('categories.index.edit'), edit_control_category_path(category) %></td>
        <td><%= link_to t('categories.index.destroy'), ['control', category], method: :delete, data: { confirm: t('categories.index.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('categories.index.new_category'), new_control_category_path, class: "btn btn-primary" %>

app/views/control/categories/new.html.erb
<%= page_title t('categories.new.new_category') %>
<% breadcrumbs.item t('categories.new.new_category') %>

<%= render 'form' %>