config/routes.rb
Ilan::Application.routes.draw do
  root "home_page#index"
  
  get "home_page/index"

  resources :categories, only: :show do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :cities, only: :show

  resources :nodes, only: [:show, :new, :create]

  namespace :control do
    get "/" => "base#index"
    resources :nodes, only: [:index, :update]
    resources :categories, except: :show
    resources :cities, except: [:show]
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    self.current_city = params[:id]

    begin
      redirect_to :back
    rescue ActionController::RedirectBackError
      redirect_to root_path
    end
  end

end

app/controllers/control/base_controller.rb
module Control
  class BaseController < ApplicationController
    before_action :set_default_breadcrumb
    layout "control"
    http_basic_authenticate_with  name:     ENV['CONTROL_USERNAME'],
                                  password: ENV["CONTROL_PASSWORD"]

    def index
    end

    private

      def set_default_breadcrumb
        unless params[:controller] == "control/base" and params[:action] == "index"
          breadcrumbs.item I18n.t('control'), control_path
        end
      end
  end
end

app/controllers/control/categories_controller.rb
module Control
  class CategoriesController < BaseController
    before_action :set_category, only: [:edit, :update, :destroy]
    before_action :set_breadcrumb, except: :index

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def edit
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to control_categories_path, notice: I18n.t('categories.flash.created')
      else
        flash[:alert] = I18n.t('categories.flash.not_created')
        render action: 'new'
      end
    end

    def update
      if @category.update(category_params)
        redirect_to control_categories_path, notice: I18n.t('categories.flash.updated')
      else
        flash[:alert] = I18n.t('categories.flash.not_updated')
        render action: 'edit'
      end
    end

    def destroy
      @category.destroy
      redirect_to control_categories_url
    end

    private
      def set_category
        @category = Category.find(params[:id])
      end

      def category_params
        params.require(:category).permit(:name, :icon)
      end

      def set_breadcrumb
        breadcrumbs.item t('categories.index.categories'), control_categories_path
      end
  end
end

app/controllers/control/cities_controller.rb
module Control
  class CitiesController < BaseController
    before_action :set_city, only: [:edit, :update, :destroy]
    before_action :set_breadcrumb, except: :index

    def index
      @cities = City.all
    end

    def new
      @city = City.new
    end

    def edit
    end

    def create
      @city = City.new(city_params)

      if @city.save
        redirect_to control_cities_path, notice: I18n.t('cities.flash.created')
      else
        flash[:alert] = I18n.t('cities.flash.not_created')
        render action: 'new'
      end
    end

    def update
      if @city.update(city_params)
        redirect_to control_cities_path, notice: I18n.t('cities.flash.updated')
      else
        flash[:alert] = I18n.t('cities.flash.not_updated')
        render action: 'edit'
      end
    end

    def destroy
      @city.destroy
        redirect_to control_cities_path
    end

    private
      def set_city
        @city = City.find(params[:id])
      end

      def city_params
        params.require(:city).permit(:name)
      end

      def set_breadcrumb
        breadcrumbs.item t('cities.index.cities'), control_cities_path
      end
  end
end

app/controllers/control/nodes_controller.rb
require 'node_filter'

module Control
  class NodesController < BaseController
    def index
      @node_filter = NodeFilter.new(params[:node_filter] || {})
      @nodes = Node.where(status: @node_filter.status)
    end

    def update
      @node = Node.find(params[:id])
      @node.send(:"#{params[:event]}!")
      redirect_to control_nodes_path
    end
  end
end

app/helpers/control/base_helper.rb
module Control::BaseHelper
  def logout_url
    protocol  = url_options[:protocol]
    user      = "invalid@"
    host      = url_options[:host]
    port      = ":" + url_options[:port].to_s
    path      = control_path
    [protocol, user, host, port, path].join
  end
end

app/views/control/cities/_form.html.erb
<%= simple_form_for(['control', @city], html: {class: "form-horizontal"}) do |f| %>
  <%= f.input :name %>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit, class: "btn-primary" %>
    </div>
  </div>
<% end %>

app/views/control/cities/edit.html.erb
<%= page_title t('cities.edit.editing_city') %>
<% breadcrumbs.item t('cities.edit.editing_city') %>

<%= render 'form' %>

app/views/control/cities/index.html.erb
<%= page_title t('cities.index.cities') %>
<% breadcrumbs.item t('cities.index.cities') %>


<table class="table">
  <thead>
    <tr>
      <th><%=t 'cities.index.city' %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= link_to t('cities.index.edit'), edit_control_city_path(city) %></td>
        <td><%= link_to t('cities.index.destroy'), 
                        ['control', city], 
                        method: :delete, 
                        data: { confirm: t('cities.index.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('cities.index.new_city'), new_control_city_path, class: "btn btn-primary" %>

app/views/control/cities/new.html.erb
<%= page_title t('cities.new.new_city') %>
<% breadcrumbs.item t('cities.new.new_city') %>

<%= render 'form' %>