config/routes.rb
Ilan::Application.routes.draw do
  root "home_page#index"
  
  get "home_page/index"

  resources :categories, only: :show do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :cities, only: :show

  resources :nodes, only: [:show, :new, :create]

  namespace :control do
    get "/" => "base#index"
    resources :nodes, only: [:index, :update]
    resources :categories, except: :show
    resources :cities, except: [:show]
  end

end

app/controllers/application_controller.rb
require './lib/breadcrumbs'
require 'default_city_policy'

class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_home_breadcrumb

  private
    helper_method :breadcrumbs
    def breadcrumbs
      @breadcrumbs ||= Breadcrumbs.new
    end

    def set_home_breadcrumb
      unless params[:controller] == "home_page" and params[:action] == "index"
        breadcrumbs.item I18n.t('home'), root_path
      end
    end

    helper_method :current_city
    def current_city
      @_current_city ||=  session[:current_city_id] && 
                            City.find_by(id: session[:current_city_id]) ||
                          DefaultCityPolicy.default_city
    end

    def current_city= id
      session[:current_city_id] = id
      @_current_city = City.find_by(id: id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title title
    render(layout: "page_header") { title }
  end
end

app/views/application/_add_new_node_button.html.erb
<%= link_to new_node_path, class: "btn btn-sm btn-primary pull-right" do %>
  <i class="glyphicon glyphicon-plus"></i> <%=t 'nodes.add_new_node' %>
<% end %>

app/views/application/_breadcrumb.html.erb
<!-- Breadcrumb -->
<% if breadcrumbs.items.present? %>
  <div class="row hidden-xs">
    <div class="col-sm-7">
      <%= render "breadcrumbs/breadcrumbs" %>
    </div>
  </div>
<% end %>
<!-- /Breadcrumb -->

app/views/application/_category_selector.html.erb
<div class="btn-group" id="category-selector">
  <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
    <%= category_name_with_icon(@category) || t('categories.index.categories') %>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <%= content_tag_for :li, Category.all do |category|%>
      <%= link_to category do %>
        <%= name_with_icon category %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/application/_city_selector.html.erb
<div class="btn-group" id="city-selector">
  <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
    <%= current_city.name %> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <%= content_tag_for :li, City.all do |city|%>
      <%= link_to city.name, city %>
    <% end %>
  </ul>
</div>

app/views/application/_foot.html.erb
  </body>
</html>

app/views/application/_footer.html.erb
<!-- Footer -->
<div class="row">
  <div class="col-sm-12">
    <div class="footer">
      <ul class="list-inline">
        <li><a href="#">Hakkımızda</a></li>
        <li><a href="#">Sıkça Sorulan Sorular</a></li>
        <li><a href="#">İletişim</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- /Footer -->

app/views/application/_head.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ilan</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

app/views/application/_header.html.erb
<!-- Header -->
<div class="header">
  <div class="container">
    <div class="row">

      <!-- Add new -->
      <div class="header-col col-sm-3 col-xs-6 pull-right">
        <%= render 'add_new_node_button' %>
      </div>

      <!-- Brand -->
      <div class="header-col col-sm-3 col-xs-6">
        <%= render 'logo' %>
      </div>

      <div class="header-col col-sm-6 col-xs-12">
        <%= render 'city_selector' %>
        <%= render 'category_selector' %>
      </div>

    </div>
  </div>
</div>
<!-- /Header -->

app/views/application/_logo.html.erb
<h3 id="logo">
  <%= link_to root_path do %>
    <i class="glyphicon glyphicon-bullhorn text-info"></i> <%=t 'site_name' %>
  <% end %>
</h3>

app/views/application/_messages.html.erb
<% if alert or notice %>
  <% if alert %>
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= alert %>
    </div>
  <% end %>

  <% if notice %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= notice %>
    </div>
  <% end %>
  <!-- /messages -->
<% end %>

app/views/application/_page_header.html.erb
<div class="page-header">
  <h3><%= yield %></h3>
</div>

app/views/application/_simple_header.html.erb
<!-- Header -->
<div class="header">
  <div class="container">
    <div class="row">

      <!-- Brand -->
      <div class="header-col col-sm-12 col-xs-12">
        <%= render 'logo' %>
      </div>

    </div>
  </div>
</div>
<!-- /Header -->